substitutions:
  name: "bedroom-fan"
  friendly_name: "Bedroom Fan"

packages:
  ifan03: !include includes/sonoff-ifan03.yaml

api:
  password: ''
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s  # 15min
