substitutions:
  name: "table_light"
  light_name: "Table Light"

<<: !include includes/sonoff_basic.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button0
    on_press:
      then:
        - light.toggle: light0
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    id: button1
    on_state:
      then:
        - light.toggle: light0

output:
  - platform: gpio
    pin: GPIO12
    id: relay0

light:
  - platform: binary
    name: ${light_name}
    id: light0
    output: relay0

status_led:
  pin:
    number: GPIO13
    inverted: true
